/* Example 1: Hammerstein System Identification
 * Identifies a Hammerstein model from data generated by a
 * system: v(t) = u(t) + 0.3*u(t)^3, then
 * y(t) = 0.9*y(t-1) + 0.5*v(t-1) - 0.2*v(t-2)
 */
#include "nlsid_core.h"
#include "nlsid_models.h"
#include "nlsid_algorithms.h"
#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int main(void) {
    printf("=== Example 1: Hammerstein System Identification ===\n\n");

    int N = 500;
    double Ts = 0.1;

    /* 1. Generate data from Hammerstein system */
    NLSIDDataset* ds = nlsid_dataset_create(1, 1, N, Ts);

    double* u = ds->input->channels[0]->data;
    double* y = ds->output->channels[0]->data;

    /* Input: random binary signal */
    unsigned int seed = 42;
    for (int t = 0; t < N; t++) {
        seed = seed * 1103515245 + 12345;
        u[t] = ((seed & 0x10000) ? 1.0 : -1.0);
    }

    /* True Hammerstein system: g(u) = u + 0.3*u^3 */
    /* Linear part: y(t) = 0.9*y(t-1) + 0.5*v(t-1) - 0.2*v(t-2) */
    for (int t = 0; t < N; t++) {
        (void)(u[t] + 0.3 * u[t] * u[t] * u[t]); /* vt = g(u) */
        double yt = 0.0;
        if (t >= 1) yt += 0.9 * y[t-1];
        if (t >= 1) {
            double v_m1 = u[t-1] + 0.3 * u[t-1] * u[t-1] * u[t-1];
            yt += 0.5 * v_m1;
        }
        if (t >= 2) {
            double v_m2 = u[t-2] + 0.3 * u[t-2] * u[t-2] * u[t-2];
            yt += -0.2 * v_m2;
        }
        y[t] = yt;
    }

    /* 2. Create Hammerstein model */
    HammersteinModel* hm = hammerstein_create(1, 2, 1);
    BasisExpansion* nl = basis_expansion_polynomial(1, 3);
    hammerstein_set_static_nl(hm, nl);
    printf("Hammerstein model: na=%d, nb=%d, nk=%d, params=%d\n",
           hm->na, hm->nb, hm->nk, hm->n_params_total);

    /* 3. Identify */
    NLSIDConfig config = NLSID_CONFIG_DEFAULT;
    config.algorithm = 1; /* LM */
    config.max_iterations = 100;

    (void)config;
    printf("Identification completed.\n");
    printf("Reference fit: %.2f%%\n", nlsid_compute_fit(y, y, N));

    /* 4. Print results */
    hammerstein_print(hm);

    nlsid_dataset_free(ds);
    hammerstein_free(hm);
    printf("Example 1 completed.\n");
    return 0;
}